### PR TITLE
Add `<GenerateDocumentationFile>` and other metadata to `.csproj`

### LINKED ISSUE #167: The XML documentation is not included the NuGet package
Hi. The XML documentation on properties and whatnot (e.g. `<summary>` tags, etc.) aren't actually included in the NuGet package. For example, `SearchParameters.Text` has this `<summary>`:
https://github.com/DAXGRID/typesense-dotnet/blob/0e59b48fbe51903c256fab332b4ac2cf7a48f3c4/src/Typesense/SearchParameters.cs#L49-L55

Yet when you install the `Typesense` package, this is nowhere to be seen:

image

[NuGet's package explorer](https://nuget.info/packages/Typesense/6.7.0) also shows that there is no `.xml` file included in the package:

image

Contrast this with [EF Core](https://nuget.info/packages/Microsoft.EntityFrameworkCore/6.0.0-rc.1.21452.10), for instance:

image

This is because the `<GenerateDocumentationFile>true</GenerateDocumentationFile>` setting is missing in your .csproj file — see [this](https://stackoverflow.com/q/43305578/7734384).
I can make a PR for this, let me know if you're on board.

### PR DESCRIPTION
**Pull request by aradalvand**
Resolves #167

I also added an icon, a description, and other metadata items that NuGet packages usually have.

### CODE REVIEW

**Comment by runeanielsen** [comment]
Hi @aradalvand, looks good!

There is only a minor issue, can you format the `.csproj` file, so the newly added code is aligned with the rest?

// Rune

**Comment by aradalvand** [comment]
@runeanielsen Done :)

**Comment by runeanielsen** [comment]
Great, I'll merge it in, thanks again! :rocket:

**Comment by runeanielsen** [comment]
@aradalvand, this has now been released in version 6.8.0

**Pull request merged**
