### PR TITLE
Add missing fields: TextMatchInfo, HnswParams and CreatedAt. Also fixes failing tests because the Store field.

### PR DESCRIPTION
**Pull request by solvingproblemswithtechnology**
Hey there!

I made some time to send a PR with some missing fields!

Thank you!

### CODE REVIEW

**Comment by solvingproblemswithtechnology** [comment]
Not sure why the tests are failing at CircleCI, for me everything passes and the given errors were fixed already.

**Comment by runeanielsen** [comment]
Hi @solvingproblemswithtechnology, I'll take a look at why the tests are failing in the next couple of days.

// Rune

**Comment by solvingproblemswithtechnology** [comment]
It seems like there's more collections that the ones created by the tests themselves. I guess you need to reset that typesense instance so it's clean again.

**Comment by runeanielsen** [comment]
The instance is always clean on each test, so it has to be something with the code you have added, since everything works before the change, but I'll look into it in a few days.

**Comment by solvingproblemswithtechnology** [comment]
Nope, the tests were failing before I changed anything, it had something to do with the field Store being null instead of true (the default value when creating a collection). But yes, I'll wait for your input.

**Comment by runeanielsen** [comment]
Hi @solvingproblemswithtechnology,

I've tried running the tests locally on the master branch HEAD commit and all tests pass without any issue, I've also repeated it multiple times without any issues. After that I tried checking out your PR and the tests fails, just like in the CI.

If you have problem with running the tests locally on the current HEAD of the master branch, lets try to fix that first before looking into this PR.

What OS are you running and are you sure that your Typesense test instance is 100% clean?

**Comment by solvingproblemswithtechnology** [comment]
Windows and yes!

I'll try again and update the PR, thanks for testing it!

**Comment by solvingproblemswithtechnology** [comment]
Just checked, the problem is that I was using the latest version, 27.0.rc35. With that version, it works. Using the 26.0, tests doesn't passes. To be clear, I didn't add those fields, and it will need a later fix when 27 is released.

image

image

**Comment by runeanielsen** [comment]
Cheers @solvingproblemswithtechnology,

I'll keep that in mind when I upgrade the library to target 0.27.0 :)

**Comment by runeanielsen** [comment]
@solvingproblemswithtechnology thanks for the contribution, I've made a new release (7.14.0) with the changes. :+1:

**Pull request merged**
