### PR TITLE
Add missing search parameters, reorganize in the same order as the of…

### PR DESCRIPTION
**Pull request by PhenX**
…ficial docs, and use reflection to build the query params

### CODE REVIEW

**Comment by runeanielsen** [comment]
Hello @PhenX,

I would prefer it if you submitted three separate pull requests, one for each of the following changes:

*  Reordering of properties in the record
*  Adding missing fields
*  Creating a new implementation to handle the building of the search query.

This would make it easier for me to review and address each change individually.

**Comment by PhenX** [comment]
Ok, I'll split the PR, but I may need to wait each PR to be merged before submitting the next one, it will be easier.

I'll do it in this order : 
 * Creating a new implementation to handle the building of the search query.
 * Reordering of properties in the record.
 * Adding missing fields.

**Comment by runeanielsen** [comment]
That is fine, thanks. :)

**Comment by PhenX** [comment]
I just noticed something about the query building : nothing is escaped, so any & or = will either break the query or make it a security issue. 
I'm thinking about using Uri.EscapeDataString or QueryString.Create, what do you think ?

**Comment by PhenX** [comment]
In fact those two options require Aspnet core ... so maybe the accepted answer on SO would be better: https://stackoverflow.com/a/829138/92315

**Comment by runeanielsen** [comment]
@PhenX, I think that is a good idea, feel free to implement it. :+1:

**Comment by PhenX** [comment]
@runeanielsen I made this PR : https://github.com/DAXGRID/typesense-dotnet/pull/127 it fixes the same issue in the export method too

**Comment by runeanielsen** [comment]
Thanks @PhenX, I'll make a new release when the missing fields has been added. :+1:

**Comment by PhenX** [comment]
Hello @runeanielsen I made the last pull request : #130

**Pull request closed without merging**
