### PR TITLE
Feature: Adding document update by filter

### PR DESCRIPTION
**Pull request by AdamGilliesSA**
Adding a function to allow updating of all documents in a collection that match a supplied filter.

https://typesense.org/docs/0.25.2/api/documents.html#update-by-query

Output From Test.

image

Please let me know if there are any issues or suggested improvements.

This would be very beneficial to the project I am working on as it will allow us to do some better targeted updates.

### CODE REVIEW

**Comment by runeanielsen** [comment]
Hi @AdamGilliesSA,

Thanks for the contribution. Can you remove the formatting changes that has been made in the README.md file and in the test file.

// Rune

**Comment by AdamGilliesSA** [comment]
@runeanielsen That should all be fixed now.

**Comment by runeanielsen** [comment]
@AdamGilliesSA do you know if `batchSize` is necessary?  Can't seem to find it specified in the documentation.

**Comment by AdamGilliesSA** [comment]
@runeanielsen I followed the function for the delete by filter operation that is currently in the code base.

```js
    public async Task<FilterDeleteResponse> DeleteDocuments(string collection, string filter, int batchSize = 40)
    {
        if (string.IsNullOrWhiteSpace(collection))
            throw new ArgumentException("cannot be null empty or whitespace", nameof(collection));
        if (string.IsNullOrWhiteSpace(filter))
            throw new ArgumentException("cannot be null empty or whitespace", nameof(filter));
        if (batchSize < 0)
            throw new ArgumentException("has to be greater than 0", nameof(batchSize));

        var response = await Delete($"/collections/{collection}/documents?filter_by={Uri.EscapeDataString(filter)}&batch_size={batchSize}").ConfigureAwait(false);
        return HandleEmptyStringJsonSerialize<FilterDeleteResponse>(response, _jsonNameCaseInsentiveTrue);
    }
```

I can find a reference in an older version of the docs but cannot see one on the latest docs.

https://typesense.org/docs/0.20.0/api/documents.html#configure-batch-size

**Comment by runeanielsen** [comment]
@AdamGilliesSA can you remove it for now, then we can add it later if it is a thing.

**Comment by runeanielsen** [comment]
@AdamGilliesSA this has now been released in version 7.3.0. Thanks for the contribution.

// Rune

**Pull request merged**
